import { TemplateDefinition } from './types';

export const TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  // 1. Offer - Bold Split (50/50 horizontal split)
  {
    id: 'offer-bold-split',
    name: 'Bold Dual Split',
    description: 'High-impact 50/50 horizontal split featuring hero imagery up top and bold offer messaging below.',
    contentType: 'offer',
    styleMood: 'bold',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#0f172a',
    zones: [
      {
        id: 'hero-photo',
        type: 'image',
        position: { x: 0, y: 0, width: 1080, height: 540 },
        style: { objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'top-logo-badge',
        type: 'logo',
        position: { x: 48, y: 48, width: 96, height: 96 },
        style: { borderRadius: 20, backgroundColor: '#ffffff', padding: 8, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'bottom-container',
        type: 'shape',
        position: { x: 0, y: 540, width: 1080, height: 540 },
        style: { backgroundColor: 'primary' },
      },
      {
        id: 'tag-badge',
        type: 'text',
        position: { x: 60, y: 580, width: 340, height: 48 },
        style: {
          fontSize: 20,
          fontWeight: 800,
          color: '#ffffff',
          backgroundColor: '#00000044',
          borderRadius: 12,
          padding: 8,
          textAlign: 'center',
          textTransform: 'uppercase',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'LIMITED TIME PROMO',
      },
      {
        id: 'main-headline',
        type: 'text',
        position: { x: 60, y: 640, width: 960, height: 190 },
        style: {
          fontSize: 48,
          fontWeight: 800,
          color: '#ffffff',
          lineHeight: 1.2,
          textAlign: 'left',
        },
        contentKey: 'headline',
      },
      {
        id: 'cta-button',
        type: 'text',
        position: { x: 60, y: 850, width: 380, height: 76 },
        style: {
          fontSize: 26,
          fontWeight: 800,
          color: '#0f172a',
          backgroundColor: '#ffffff',
          borderRadius: 20,
          textAlign: 'center',
          textTransform: 'uppercase',
          letterSpacing: 1,
        },
        contentKey: 'ctaText',
      },
      {
        id: 'footer-business-name',
        type: 'text',
        position: { x: 60, y: 955, width: 960, height: 45 },
        style: {
          fontSize: 22,
          fontWeight: 600,
          color: '#ffffffcc',
          textAlign: 'left',
        },
        contentKey: 'businessName',
      },
    ],
  },

  // 2. Offer - Minimal Inset Card
  {
    id: 'offer-minimal-card',
    name: 'Clean Inset Showcase',
    description: 'Refined minimalist layout with generous whitespace, rounded inset photo card, and clear promotional typography.',
    contentType: 'offer',
    styleMood: 'minimal',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#f8fafc',
    zones: [
      {
        id: 'header-logo',
        type: 'logo',
        position: { x: 80, y: 60, width: 80, height: 80 },
        style: { borderRadius: 16, backgroundColor: '#ffffff', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'header-name',
        type: 'text',
        position: { x: 180, y: 80, width: 600, height: 44 },
        style: { fontSize: 26, fontWeight: 700, color: '#0f172a', textAlign: 'left' },
        contentKey: 'businessName',
      },
      {
        id: 'center-photo-card',
        type: 'image',
        position: { x: 80, y: 170, width: 920, height: 500 },
        style: { borderRadius: 28, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'tag-pill',
        type: 'text',
        position: { x: 80, y: 700, width: 260, height: 42 },
        style: {
          fontSize: 18,
          fontWeight: 700,
          color: 'primary',
          backgroundColor: '#e0e7ff',
          borderRadius: 24,
          textAlign: 'center',
          textTransform: 'uppercase',
          letterSpacing: 1,
        },
        contentKey: 'tag',
        staticText: 'SPECIAL OFFER',
      },
      {
        id: 'headline',
        type: 'text',
        position: { x: 80, y: 755, width: 920, height: 150 },
        style: { fontSize: 44, fontWeight: 800, color: '#0f172a', lineHeight: 1.25, textAlign: 'left' },
        contentKey: 'headline',
      },
      {
        id: 'cta-pill',
        type: 'text',
        position: { x: 80, y: 925, width: 340, height: 70 },
        style: {
          fontSize: 24,
          fontWeight: 700,
          color: '#ffffff',
          backgroundColor: 'primary',
          borderRadius: 35,
          textAlign: 'center',
        },
        contentKey: 'ctaText',
      },
    ],
  },

  // 3. Offer - Premium Dark Luxury
  {
    id: 'offer-premium-dark',
    name: 'Obsidian Prestige',
    description: 'High-end dark luxury layout with moody cinematic backdrop, gold/amber accents, and executive typography.',
    contentType: 'offer',
    styleMood: 'premium',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#090d16',
    zones: [
      {
        id: 'dark-photo-bg',
        type: 'image',
        position: { x: 0, y: 0, width: 1080, height: 1080 },
        style: { objectFit: 'cover', opacity: 0.35 },
        contentKey: 'photoUrl',
      },
      {
        id: 'vignette-overlay',
        type: 'shape',
        position: { x: 0, y: 0, width: 1080, height: 1080 },
        style: { backgroundColor: '#090d16bb' },
      },
      {
        id: 'luxury-accent-line',
        type: 'shape',
        position: { x: 90, y: 110, width: 120, height: 6 },
        style: { backgroundColor: '#f59e0b', borderRadius: 3 },
      },
      {
        id: 'brand-logo',
        type: 'logo',
        position: { x: 90, y: 140, width: 90, height: 90 },
        style: { borderRadius: 18, backgroundColor: '#ffffff15', padding: 8, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'business-title',
        type: 'text',
        position: { x: 205, y: 160, width: 785, height: 50 },
        style: { fontSize: 26, fontWeight: 700, color: '#f8fafc', letterSpacing: 2, textTransform: 'uppercase' },
        contentKey: 'businessName',
      },
      {
        id: 'exclusive-badge',
        type: 'text',
        position: { x: 90, y: 380, width: 320, height: 46 },
        style: {
          fontSize: 18,
          fontWeight: 700,
          color: '#fbbf24',
          backgroundColor: '#f59e0b20',
          borderRadius: 8,
          borderWidth: 1,
          borderColor: '#f59e0b60',
          textAlign: 'center',
          letterSpacing: 2,
          textTransform: 'uppercase',
        },
        contentKey: 'tag',
        staticText: 'EXCLUSIVE INVITATION',
      },
      {
        id: 'headline',
        type: 'text',
        position: { x: 90, y: 450, width: 900, height: 230 },
        style: { fontSize: 50, fontWeight: 800, color: '#ffffff', lineHeight: 1.2 },
        contentKey: 'headline',
      },
      {
        id: 'caption-summary',
        type: 'text',
        position: { x: 90, y: 700, width: 900, height: 130 },
        style: { fontSize: 24, fontWeight: 400, color: '#cbd5e1', lineHeight: 1.4 },
        contentKey: 'caption',
      },
      {
        id: 'cta-gold',
        type: 'text',
        position: { x: 90, y: 865, width: 380, height: 75 },
        style: {
          fontSize: 24,
          fontWeight: 800,
          color: '#090d16',
          backgroundColor: '#f59e0b',
          borderRadius: 14,
          textAlign: 'center',
          textTransform: 'uppercase',
          letterSpacing: 1,
        },
        contentKey: 'ctaText',
      },
    ],
  },

  // 4. Offer - Playful Pop
  {
    id: 'offer-playful-pop',
    name: 'Vibrant Pop & Savings',
    description: 'Dynamic playful layout featuring a circular hero image cutout, colorful discount badge, and punchy typography.',
    contentType: 'offer',
    styleMood: 'playful',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#fffbeb',
    zones: [
      {
        id: 'top-accent-bar',
        type: 'shape',
        position: { x: 0, y: 0, width: 1080, height: 24 },
        style: { backgroundColor: 'primary' },
      },
      {
        id: 'round-photo-cutout',
        type: 'image',
        position: { x: 80, y: 80, width: 420, height: 420 },
        style: { borderRadius: 9999, borderWidth: 12, borderColor: '#ffffff', objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'fun-badge',
        type: 'text',
        position: { x: 530, y: 100, width: 470, height: 60 },
        style: {
          fontSize: 24,
          fontWeight: 800,
          color: '#ffffff',
          backgroundColor: '#ef4444',
          borderRadius: 30,
          textAlign: 'center',
          textTransform: 'uppercase',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'SPECIAL SAVINGS',
      },
      {
        id: 'logo-corner',
        type: 'logo',
        position: { x: 530, y: 185, width: 80, height: 80 },
        style: { borderRadius: 20, backgroundColor: '#ffffff', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'business-sub',
        type: 'text',
        position: { x: 630, y: 205, width: 370, height: 40 },
        style: { fontSize: 24, fontWeight: 700, color: '#1e293b' },
        contentKey: 'businessName',
      },
      {
        id: 'headline-main',
        type: 'text',
        position: { x: 80, y: 530, width: 920, height: 210 },
        style: { fontSize: 52, fontWeight: 900, color: '#0f172a', lineHeight: 1.15 },
        contentKey: 'headline',
      },
      {
        id: 'big-cta-button',
        type: 'text',
        position: { x: 80, y: 770, width: 920, height: 96 },
        style: {
          fontSize: 32,
          fontWeight: 900,
          color: '#ffffff',
          backgroundColor: 'primary',
          borderRadius: 48,
          textAlign: 'center',
          textTransform: 'uppercase',
          letterSpacing: 2,
        },
        contentKey: 'ctaText',
      },
      {
        id: 'caption-subtext',
        type: 'text',
        position: { x: 80, y: 895, width: 920, height: 80 },
        style: { fontSize: 22, fontWeight: 500, color: '#64748b', textAlign: 'center', lineHeight: 1.3 },
        contentKey: 'caption',
      },
    ],
  },

  // 5. Festival - Festive Burst
  {
    id: 'festival-festive-burst',
    name: 'Celebratory Festive Glow',
    description: 'Radiant celebratory layout with warm festive colors, celebratory badge, and prominent seasonal greeting.',
    contentType: 'festival',
    styleMood: 'festive',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#450a0a',
    zones: [
      {
        id: 'festive-photo-window',
        type: 'image',
        position: { x: 100, y: 440, width: 880, height: 420 },
        style: { borderRadius: 32, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'gold-greeting-pill',
        type: 'text',
        position: { x: 290, y: 90, width: 500, height: 56 },
        style: {
          fontSize: 22,
          fontWeight: 800,
          color: '#78350f',
          backgroundColor: '#fef3c7',
          borderRadius: 28,
          textAlign: 'center',
          letterSpacing: 2,
          textTransform: 'uppercase',
        },
        contentKey: 'tag',
        staticText: 'SEASON OF CELEBRATION',
      },
      {
        id: 'festive-headline',
        type: 'text',
        position: { x: 80, y: 170, width: 920, height: 230 },
        style: {
          fontSize: 54,
          fontWeight: 900,
          color: '#fef08a',
          textAlign: 'center',
          lineHeight: 1.2,
        },
        contentKey: 'headline',
      },
      {
        id: 'footer-logo',
        type: 'logo',
        position: { x: 100, y: 890, width: 90, height: 90 },
        style: { borderRadius: 20, backgroundColor: '#ffffff', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'footer-greeting',
        type: 'text',
        position: { x: 215, y: 915, width: 765, height: 50 },
        style: { fontSize: 26, fontWeight: 700, color: '#fef3c7' },
        contentKey: 'businessName',
      },
    ],
  },

  // 6. Festival - Bold Framed Holiday
  {
    id: 'festival-bold-frame',
    name: 'Festive Border Showcase',
    description: 'Prominent festive border frame surrounding high-contrast business imagery and heartfelt seasonal wishes.',
    contentType: 'festival',
    styleMood: 'bold',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#1e1b4b',
    zones: [
      {
        id: 'top-photo-frame',
        type: 'image',
        position: { x: 60, y: 60, width: 960, height: 540 },
        style: { borderRadius: 24, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'lower-banner-card',
        type: 'shape',
        position: { x: 60, y: 630, width: 960, height: 390 },
        style: { backgroundColor: '#312e81', borderRadius: 24 },
      },
      {
        id: 'badge-festive',
        type: 'text',
        position: { x: 100, y: 660, width: 360, height: 44 },
        style: {
          fontSize: 18,
          fontWeight: 800,
          color: '#fef08a',
          backgroundColor: '#4338ca',
          borderRadius: 12,
          textAlign: 'center',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'WARMEST GREETINGS',
      },
      {
        id: 'headline',
        type: 'text',
        position: { x: 100, y: 720, width: 880, height: 160 },
        style: { fontSize: 44, fontWeight: 800, color: '#ffffff', lineHeight: 1.25 },
        contentKey: 'headline',
      },
      {
        id: 'bottom-row-logo',
        type: 'logo',
        position: { x: 100, y: 900, width: 70, height: 70 },
        style: { borderRadius: 14, backgroundColor: '#ffffff', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'bottom-row-name',
        type: 'text',
        position: { x: 190, y: 915, width: 790, height: 40 },
        style: { fontSize: 24, fontWeight: 700, color: '#e0e7ff' },
        contentKey: 'businessName',
      },
    ],
  },

  // 7. Festival - Playful Celebration
  {
    id: 'festival-playful-celebration',
    name: 'Joyful Celebration Fiesta',
    description: 'Lively cheerful layout with playful circular image framing, festive tag, and warm social copy.',
    contentType: 'festival',
    styleMood: 'playful',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#042f2e',
    zones: [
      {
        id: 'circle-photo',
        type: 'image',
        position: { x: 560, y: 90, width: 440, height: 440 },
        style: { borderRadius: 9999, borderWidth: 8, borderColor: '#2dd4bf', objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'festive-tag',
        type: 'text',
        position: { x: 80, y: 110, width: 340, height: 48 },
        style: {
          fontSize: 20,
          fontWeight: 800,
          color: '#134e4a',
          backgroundColor: '#99f6e4',
          borderRadius: 14,
          textAlign: 'center',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'HOLIDAY VIBES',
      },
      {
        id: 'festive-headline',
        type: 'text',
        position: { x: 80, y: 180, width: 450, height: 320 },
        style: { fontSize: 46, fontWeight: 900, color: '#ffffff', lineHeight: 1.2 },
        contentKey: 'headline',
      },
      {
        id: 'greeting-card-bottom',
        type: 'shape',
        position: { x: 80, y: 570, width: 920, height: 430 },
        style: { backgroundColor: '#115e59', borderRadius: 28 },
      },
      {
        id: 'caption-text',
        type: 'text',
        position: { x: 120, y: 610, width: 840, height: 180 },
        style: { fontSize: 26, fontWeight: 400, color: '#ccfbf1', lineHeight: 1.45 },
        contentKey: 'caption',
      },
      {
        id: 'logo-brand',
        type: 'logo',
        position: { x: 120, y: 830, width: 80, height: 80 },
        style: { borderRadius: 18, backgroundColor: '#ffffff', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'company-name-sig',
        type: 'text',
        position: { x: 220, y: 850, width: 740, height: 50 },
        style: { fontSize: 26, fontWeight: 700, color: '#ffffff' },
        contentKey: 'businessName',
      },
    ],
  },

  // 8. Festival - Minimal Greeting
  {
    id: 'festival-minimal-greeting',
    name: 'Serene Minimal Blessing',
    description: 'Poised, elegant holiday greeting with delicate typography and serene low-contrast photo blend.',
    contentType: 'festival',
    styleMood: 'minimal',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#18181b',
    zones: [
      {
        id: 'subtle-photo-backdrop',
        type: 'image',
        position: { x: 0, y: 0, width: 1080, height: 1080 },
        style: { objectFit: 'cover', opacity: 0.28 },
        contentKey: 'photoUrl',
      },
      {
        id: 'ornament-badge',
        type: 'text',
        position: { x: 340, y: 140, width: 400, height: 40 },
        style: {
          fontSize: 18,
          fontWeight: 700,
          color: '#fbbf24',
          textAlign: 'center',
          letterSpacing: 4,
          textTransform: 'uppercase',
        },
        contentKey: 'tag',
        staticText: 'PEACE & PROSPERITY',
      },
      {
        id: 'greeting-headline',
        type: 'text',
        position: { x: 120, y: 220, width: 840, height: 280 },
        style: {
          fontSize: 52,
          fontWeight: 800,
          color: '#f4f4f5',
          textAlign: 'center',
          lineHeight: 1.25,
        },
        contentKey: 'headline',
      },
      {
        id: 'divider-line',
        type: 'shape',
        position: { x: 440, y: 530, width: 200, height: 3 },
        style: { backgroundColor: '#fbbf2488' },
      },
      {
        id: 'greeting-message',
        type: 'text',
        position: { x: 160, y: 570, width: 760, height: 180 },
        style: {
          fontSize: 24,
          fontWeight: 400,
          color: '#d4d4d8',
          textAlign: 'center',
          lineHeight: 1.5,
        },
        contentKey: 'caption',
      },
      {
        id: 'center-logo',
        type: 'logo',
        position: { x: 490, y: 800, width: 100, height: 100 },
        style: { borderRadius: 20, backgroundColor: '#ffffff', padding: 8, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'center-business-name',
        type: 'text',
        position: { x: 140, y: 920, width: 800, height: 50 },
        style: { fontSize: 24, fontWeight: 700, color: '#a1a1aa', textAlign: 'center' },
        contentKey: 'businessName',
      },
    ],
  },

  // 9. Service - Professional Column Split (40/60 vertical)
  {
    id: 'service-professional-split',
    name: 'Executive Column Split',
    description: 'Authoritative vertical column split with left-side value proposition and right-side crisp service photography.',
    contentType: 'service',
    styleMood: 'professional',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#0f172a',
    zones: [
      {
        id: 'left-column-bg',
        type: 'shape',
        position: { x: 0, y: 0, width: 520, height: 1080 },
        style: { backgroundColor: 'primary' },
      },
      {
        id: 'right-photo-column',
        type: 'image',
        position: { x: 520, y: 0, width: 560, height: 1080 },
        style: { objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'left-logo',
        type: 'logo',
        position: { x: 60, y: 70, width: 90, height: 90 },
        style: { borderRadius: 18, backgroundColor: '#ffffff', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'company-name',
        type: 'text',
        position: { x: 60, y: 190, width: 400, height: 50 },
        style: { fontSize: 24, fontWeight: 700, color: '#ffffffcc' },
        contentKey: 'businessName',
      },
      {
        id: 'service-tag',
        type: 'text',
        position: { x: 60, y: 260, width: 300, height: 40 },
        style: {
          fontSize: 16,
          fontWeight: 800,
          color: '#ffffff',
          backgroundColor: '#00000030',
          borderRadius: 8,
          padding: 6,
          textAlign: 'center',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'VERIFIED SERVICE',
      },
      {
        id: 'service-headline',
        type: 'text',
        position: { x: 60, y: 320, width: 400, height: 280 },
        style: { fontSize: 40, fontWeight: 800, color: '#ffffff', lineHeight: 1.2 },
        contentKey: 'headline',
      },
      {
        id: 'service-caption',
        type: 'text',
        position: { x: 60, y: 620, width: 400, height: 200 },
        style: { fontSize: 20, fontWeight: 400, color: '#ffffffdd', lineHeight: 1.4 },
        contentKey: 'caption',
      },
      {
        id: 'cta-action',
        type: 'text',
        position: { x: 60, y: 860, width: 380, height: 75 },
        style: {
          fontSize: 22,
          fontWeight: 800,
          color: '#0f172a',
          backgroundColor: '#ffffff',
          borderRadius: 16,
          textAlign: 'center',
          textTransform: 'uppercase',
        },
        contentKey: 'ctaText',
      },
    ],
  },

  // 10. Service - Minimal Modern Showcase
  {
    id: 'service-minimal-modern',
    name: 'Modern Precision Studio',
    description: 'Clean high-readability layout with top brand navigation, large wide photo card, and clear call-to-action.',
    contentType: 'service',
    styleMood: 'minimal',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#ffffff',
    zones: [
      {
        id: 'nav-logo',
        type: 'logo',
        position: { x: 80, y: 60, width: 80, height: 80 },
        style: { borderRadius: 16, backgroundColor: '#f1f5f9', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'nav-name',
        type: 'text',
        position: { x: 180, y: 78, width: 820, height: 44 },
        style: { fontSize: 26, fontWeight: 700, color: '#0f172a' },
        contentKey: 'businessName',
      },
      {
        id: 'hero-photo-banner',
        type: 'image',
        position: { x: 80, y: 160, width: 920, height: 480 },
        style: { borderRadius: 24, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'headline-text',
        type: 'text',
        position: { x: 80, y: 670, width: 920, height: 140 },
        style: { fontSize: 44, fontWeight: 800, color: '#0f172a', lineHeight: 1.2 },
        contentKey: 'headline',
      },
      {
        id: 'caption-lead',
        type: 'text',
        position: { x: 80, y: 830, width: 580, height: 150 },
        style: { fontSize: 22, fontWeight: 400, color: '#475569', lineHeight: 1.45 },
        contentKey: 'caption',
      },
      {
        id: 'cta-pill-button',
        type: 'text',
        position: { x: 700, y: 855, width: 300, height: 75 },
        style: {
          fontSize: 22,
          fontWeight: 700,
          color: '#ffffff',
          backgroundColor: 'primary',
          borderRadius: 38,
          textAlign: 'center',
        },
        contentKey: 'ctaText',
      },
    ],
  },

  // 11. Service - Bold Spotlight
  {
    id: 'service-bold-spotlight',
    name: 'Dramatic Spotlight Impact',
    description: 'Full-bleed photographic backdrop with a dramatic dark lower-third spotlight card and high-contrast typography.',
    contentType: 'service',
    styleMood: 'bold',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#020617',
    zones: [
      {
        id: 'full-bleed-photo',
        type: 'image',
        position: { x: 0, y: 0, width: 1080, height: 1080 },
        style: { objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'spotlight-card',
        type: 'shape',
        position: { x: 60, y: 460, width: 960, height: 560 },
        style: { backgroundColor: '#020617ee', borderRadius: 28, borderWidth: 1, borderColor: '#334155' },
      },
      {
        id: 'spotlight-tag',
        type: 'text',
        position: { x: 110, y: 510, width: 320, height: 46 },
        style: {
          fontSize: 18,
          fontWeight: 800,
          color: '#020617',
          backgroundColor: '#38bdf8',
          borderRadius: 12,
          textAlign: 'center',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'PREMIER SERVICE',
      },
      {
        id: 'spotlight-headline',
        type: 'text',
        position: { x: 110, y: 575, width: 860, height: 190 },
        style: { fontSize: 46, fontWeight: 800, color: '#ffffff', lineHeight: 1.2 },
        contentKey: 'headline',
      },
      {
        id: 'spotlight-cta',
        type: 'text',
        position: { x: 110, y: 785, width: 360, height: 75 },
        style: {
          fontSize: 24,
          fontWeight: 800,
          color: '#ffffff',
          backgroundColor: 'primary',
          borderRadius: 18,
          textAlign: 'center',
        },
        contentKey: 'ctaText',
      },
      {
        id: 'spotlight-logo',
        type: 'logo',
        position: { x: 110, y: 890, width: 70, height: 70 },
        style: { borderRadius: 16, backgroundColor: '#ffffff', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'spotlight-business',
        type: 'text',
        position: { x: 195, y: 905, width: 775, height: 40 },
        style: { fontSize: 24, fontWeight: 700, color: '#94a3b8' },
        contentKey: 'businessName',
      },
    ],
  },

  // 12. Service - Premium Executive
  {
    id: 'service-premium-executive',
    name: 'Executive Tier Trust',
    description: 'Corporate indigo & gold luxury layout with certified credibility framing and centered corporate insignia.',
    contentType: 'service',
    styleMood: 'premium',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#0f172a',
    zones: [
      {
        id: 'gold-border-frame',
        type: 'shape',
        position: { x: 40, y: 40, width: 1000, height: 1000 },
        style: { borderWidth: 2, borderColor: '#e2e8f030', borderRadius: 24 },
      },
      {
        id: 'exec-logo',
        type: 'logo',
        position: { x: 490, y: 70, width: 100, height: 100 },
        style: { borderRadius: 20, backgroundColor: '#ffffff', padding: 8, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'exec-name',
        type: 'text',
        position: { x: 140, y: 190, width: 800, height: 45 },
        style: { fontSize: 24, fontWeight: 700, color: '#94a3b8', textAlign: 'center', letterSpacing: 2 },
        contentKey: 'businessName',
      },
      {
        id: 'exec-photo-card',
        type: 'image',
        position: { x: 140, y: 250, width: 800, height: 430 },
        style: { borderRadius: 20, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'exec-headline',
        type: 'text',
        position: { x: 100, y: 710, width: 880, height: 140 },
        style: { fontSize: 42, fontWeight: 800, color: '#f8fafc', textAlign: 'center', lineHeight: 1.25 },
        contentKey: 'headline',
      },
      {
        id: 'exec-cta',
        type: 'text',
        position: { x: 360, y: 875, width: 360, height: 75 },
        style: {
          fontSize: 22,
          fontWeight: 800,
          color: '#0f172a',
          backgroundColor: '#f8fafc',
          borderRadius: 16,
          textAlign: 'center',
          letterSpacing: 1,
        },
        contentKey: 'ctaText',
      },
    ],
  },

  // 13. Educational - Minimal Quote Editorial
  {
    id: 'educational-minimal-quote',
    name: 'Editorial Insight & Wisdom',
    description: 'Editorial article-style layout with large quote headline, illustrative side photo, and verified author signature.',
    contentType: 'educational',
    styleMood: 'minimal',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#f8fafc',
    zones: [
      {
        id: 'tag-did-you-know',
        type: 'text',
        position: { x: 90, y: 80, width: 320, height: 44 },
        style: {
          fontSize: 18,
          fontWeight: 800,
          color: 'primary',
          backgroundColor: '#e2e8f0',
          borderRadius: 10,
          textAlign: 'center',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'DID YOU KNOW?',
      },
      {
        id: 'quote-headline',
        type: 'text',
        position: { x: 90, y: 150, width: 900, height: 320 },
        style: { fontSize: 52, fontWeight: 800, color: '#0f172a', lineHeight: 1.2 },
        contentKey: 'headline',
      },
      {
        id: 'divider',
        type: 'shape',
        position: { x: 90, y: 495, width: 900, height: 3 },
        style: { backgroundColor: '#cbd5e1' },
      },
      {
        id: 'side-photo',
        type: 'image',
        position: { x: 90, y: 530, width: 380, height: 430 },
        style: { borderRadius: 24, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'caption-body',
        type: 'text',
        position: { x: 510, y: 540, width: 480, height: 280 },
        style: { fontSize: 24, fontWeight: 400, color: '#334155', lineHeight: 1.45 },
        contentKey: 'caption',
      },
      {
        id: 'author-logo',
        type: 'logo',
        position: { x: 510, y: 865, width: 70, height: 70 },
        style: { borderRadius: 16, backgroundColor: '#ffffff', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'author-name',
        type: 'text',
        position: { x: 595, y: 880, width: 395, height: 40 },
        style: { fontSize: 22, fontWeight: 700, color: '#0f172a' },
        contentKey: 'businessName',
      },
    ],
  },

  // 14. Educational - Bold Industry Tips
  {
    id: 'educational-bold-tips',
    name: 'Bold Masterclass Tips',
    description: 'High-contrast knowledge card with bold top header block, visual photo anchor, and key takeaways.',
    contentType: 'educational',
    styleMood: 'bold',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#f1f5f9',
    zones: [
      {
        id: 'top-color-block',
        type: 'shape',
        position: { x: 0, y: 0, width: 1080, height: 420 },
        style: { backgroundColor: 'primary' },
      },
      {
        id: 'tag-masterclass',
        type: 'text',
        position: { x: 80, y: 60, width: 300, height: 44 },
        style: {
          fontSize: 18,
          fontWeight: 800,
          color: '#ffffff',
          backgroundColor: '#00000035',
          borderRadius: 12,
          textAlign: 'center',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'PRO TIP GUIDE',
      },
      {
        id: 'top-headline',
        type: 'text',
        position: { x: 80, y: 130, width: 920, height: 240 },
        style: { fontSize: 48, fontWeight: 900, color: '#ffffff', lineHeight: 1.2 },
        contentKey: 'headline',
      },
      {
        id: 'split-photo',
        type: 'image',
        position: { x: 80, y: 460, width: 440, height: 440 },
        style: { borderRadius: 24, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'split-caption',
        type: 'text',
        position: { x: 560, y: 470, width: 440, height: 420 },
        style: { fontSize: 24, fontWeight: 400, color: '#1e293b', lineHeight: 1.45 },
        contentKey: 'caption',
      },
      {
        id: 'footer-bar',
        type: 'text',
        position: { x: 80, y: 940, width: 920, height: 50 },
        style: { fontSize: 22, fontWeight: 700, color: '#64748b', textAlign: 'left' },
        contentKey: 'businessName',
      },
    ],
  },

  // 15. Educational - Professional Knowledge Guide
  {
    id: 'educational-professional-guide',
    name: 'Corporate Best Practices',
    description: 'Grid layout featuring side-by-side photo and guide takeaways, complete with bottom contact CTA.',
    contentType: 'educational',
    styleMood: 'professional',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#ffffff',
    zones: [
      {
        id: 'header-logo',
        type: 'logo',
        position: { x: 60, y: 50, width: 80, height: 80 },
        style: { borderRadius: 16, backgroundColor: '#f8fafc', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'header-brand',
        type: 'text',
        position: { x: 160, y: 70, width: 860, height: 40 },
        style: { fontSize: 24, fontWeight: 700, color: '#0f172a' },
        contentKey: 'businessName',
      },
      {
        id: 'guide-photo',
        type: 'image',
        position: { x: 60, y: 160, width: 460, height: 620 },
        style: { borderRadius: 20, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'guide-card',
        type: 'shape',
        position: { x: 550, y: 160, width: 470, height: 620 },
        style: { backgroundColor: '#f8fafc', borderRadius: 20, borderWidth: 1, borderColor: '#e2e8f0' },
      },
      {
        id: 'guide-tag',
        type: 'text',
        position: { x: 590, y: 200, width: 260, height: 40 },
        style: {
          fontSize: 16,
          fontWeight: 800,
          color: 'primary',
          backgroundColor: '#e0e7ff',
          borderRadius: 8,
          textAlign: 'center',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'INDUSTRY ADVICE',
      },
      {
        id: 'guide-headline',
        type: 'text',
        position: { x: 590, y: 260, width: 390, height: 230 },
        style: { fontSize: 36, fontWeight: 800, color: '#0f172a', lineHeight: 1.25 },
        contentKey: 'headline',
      },
      {
        id: 'guide-caption',
        type: 'text',
        position: { x: 590, y: 510, width: 390, height: 230 },
        style: { fontSize: 20, fontWeight: 400, color: '#475569', lineHeight: 1.4 },
        contentKey: 'caption',
      },
      {
        id: 'bottom-banner',
        type: 'shape',
        position: { x: 60, y: 810, width: 960, height: 180 },
        style: { backgroundColor: 'primary', borderRadius: 20 },
      },
      {
        id: 'banner-cta-text',
        type: 'text',
        position: { x: 100, y: 870, width: 880, height: 60 },
        style: { fontSize: 28, fontWeight: 800, color: '#ffffff', textAlign: 'center' },
        contentKey: 'ctaText',
      },
    ],
  },

  // 16. Educational - Premium Deep Insight
  {
    id: 'educational-premium-insight',
    name: 'Obsidian Analytical Insight',
    description: 'Deep obsidian backdrop with widescreen cinematic image slice, analytical headline, and verified credibility badge.',
    contentType: 'educational',
    styleMood: 'premium',
    canvas: { width: 1080, height: 1080 },
    defaultBackground: '#0b0f19',
    zones: [
      {
        id: 'top-logo',
        type: 'logo',
        position: { x: 80, y: 60, width: 70, height: 70 },
        style: { borderRadius: 14, backgroundColor: '#1e293b', padding: 6, objectFit: 'contain' },
        contentKey: 'logoUrl',
      },
      {
        id: 'top-name',
        type: 'text',
        position: { x: 170, y: 75, width: 830, height: 40 },
        style: { fontSize: 24, fontWeight: 700, color: '#94a3b8', letterSpacing: 2 },
        contentKey: 'businessName',
      },
      {
        id: 'cinematic-photo-slice',
        type: 'image',
        position: { x: 80, y: 160, width: 920, height: 400 },
        style: { borderRadius: 20, objectFit: 'cover' },
        contentKey: 'photoUrl',
      },
      {
        id: 'insight-badge',
        type: 'text',
        position: { x: 80, y: 590, width: 280, height: 42 },
        style: {
          fontSize: 16,
          fontWeight: 800,
          color: '#38bdf8',
          backgroundColor: '#0369a130',
          borderRadius: 10,
          textAlign: 'center',
          letterSpacing: 2,
        },
        contentKey: 'tag',
        staticText: 'DEEP DIVE REPORT',
      },
      {
        id: 'headline',
        type: 'text',
        position: { x: 80, y: 650, width: 920, height: 150 },
        style: { fontSize: 42, fontWeight: 800, color: '#f8fafc', lineHeight: 1.25 },
        contentKey: 'headline',
      },
      {
        id: 'caption',
        type: 'text',
        position: { x: 80, y: 820, width: 920, height: 120 },
        style: { fontSize: 22, fontWeight: 400, color: '#94a3b8', lineHeight: 1.4 },
        contentKey: 'caption',
      },
      {
        id: 'footer-status',
        type: 'text',
        position: { x: 80, y: 960, width: 920, height: 40 },
        style: { fontSize: 18, fontWeight: 600, color: '#64748b' },
        staticText: 'Verified Business Publication • Insights & Best Practices',
      },
    ],
  },
];

export function getTemplateById(id: string): TemplateDefinition | undefined {
  return TEMPLATE_DEFINITIONS.find((t) => t.id === id);
}

export function getAllTemplates(): TemplateDefinition[] {
  return TEMPLATE_DEFINITIONS;
}

export function getTemplatesByFilter(contentType?: string, styleMood?: string): TemplateDefinition[] {
  return TEMPLATE_DEFINITIONS.filter((t) => {
    if (contentType && t.contentType !== contentType) return false;
    if (styleMood && t.styleMood !== styleMood) return false;
    return true;
  });
}
